name: Update

# https://docs.github.com/cn/actions/reference/events-that-trigger-workflows#workflow_dispatch
on:
  # 手动触发
  workflow_dispatch:
  # 定时任务
  schedule:
    # https://crontab.guru/
    # UTC 时间，中国时区应减 8
    #         ┌────────── minute (0 - 59)
    #         │ ┌──────── hour (0 - 23)
    #         │ │ ┌────── day of the month (1 - 31)
    #         │ │ │ ┌──── month (1 - 12 or JAN-DEC)
    #         │ │ │ │ ┌── day of the week (0 - 6 or SUN-SAT)
    #         │ │ │ │ │
    - cron: '0 0 * * *'

env:
  TZ: Asia/Shanghai

jobs:
  Update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Update playlists
        run: pnpm build

      - name: Get changes
        run: |
          git status
          echo "CHANGES=$(git status --porcelain | grep -q 'VERSION'; echo $?)" >> $GITHUB_ENV

      - name: Commit Update
        if: ${{ env.CHANGES == 0 }}
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "[Bot] Update Playlists"
          git push

      - name: Purge CDN cache
        if: ${{ env.CHANGES == 0 }}
        run: |
          sleep 3s
          pnpm cdn:purge
